### ISSUE TITLE
Can't see new word after suggest button refresh

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#38] opened 2015-05-12 11:34 UTC
Currently when a user hits the suggest button, the page refreshes at the same point i.e. the word changes above but the user can't see that it has changed without scrolling up. We should change that.

**Comment by hcatlin** [comment] 2015-07-19 18:45
On which page? Project pages?

**Comment by interestinall** [comment] 2015-07-20 10:33
Project pages. As it loads to the next word we are left staring at the suggest button.

**Comment by malrase** [comment] 2015-09-02 17:28
I believe that this is caused by not scrolling to top on route transitions. This should have been fixed with https://github.com/wordset/wordset-ui/commit/cc9fc8fa8667988030f8645ae0174e9ea851c660 – similar to issue wordset/wordset-ui#133

**Closed** 2015-09-02 17:28 UTC
Labels: enhancement
